### ISSUE TITLE
Access Public Playlist

### ISSUE THREAD

**Issue by gylippus** [zwand19/CordovaAppleMusic#1]
Awesome progress on this. This may be a question more than a real request or issue, but do you know if there is a way within the new API to query and play public playlists? Something like this: https://tools.applemusic.com/en-us/details/pl.944580390485470b832ba7efb67c399d?country=us

I couldn't find anything exact looking through the Apple documentation, and in the end I'd want to get it working through this plugin as well. 

Just curious how in depth you planned to go with this and if that was on your mind. Look forward to seeing what you come up with for this plugin!

**Comment by zwand19** [comment]
Disclaimer - I didn't know the first thing about Objective-C before working on this plugin so I'm certainly not well-versed in any of this.

Yeah it seems like apple's documentation around all of this functionality is lacking/incomplete. This method was added in 9.3 https://developer.apple.com/reference/mediaplayer/mpmedialibrary/1621273-getplaylistwithuuid but has no documentation.

http://stackoverflow.com/questions/36902854/error-when-using-mpmediaplaylist-additemwithproductidcompletionhandler might help you.

I don't really have any long term plans for this plugin. I just started this because we need apple music integration for an app I am working on and I thought others might find this useful/be able to help me with it. I've just been adding methods as we need them in my project. If anyone has suggestions/requests I'd be happy to try to work through them if I find some free time.
